<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MgtOcr.Core\MgtOcr.Core.csproj" />
    <ProjectReference Include="..\MgtOcr.Ocr\MgtOcr.Ocr.csproj" />
    <ProjectReference Include="..\MgtOcr.Data\MgtOcr.Data.csproj" />
    <ProjectReference Include="..\MgtOcr.Sap\MgtOcr.Sap.csproj" />
  </ItemGroup>

</Project>
