@echo off
chcp 65001 >nul
cd /d "%~dp0"
echo ============================================
echo  ติดตั้งฐานข้อมูล MGT_Document_OCR (schema ocr)
echo ============================================
echo [1/6] สร้างตารางหลัก ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/01_schema.sql
echo [2/6] สร้างตารางการแปลงหน่วย ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/02_uom.sql
echo [3/6] ใส่ข้อมูล Master ตัวอย่าง ...
python app/tools/seed.py
echo [4/6] เพิ่มคอลัมน์รหัสของ SAP ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/03_sapcode.sql
echo [5/6] ใส่กฎการแปลงหน่วยตัวอย่าง ...
python app/tools/seed_uom.py
echo [6/7] เติมรหัสของ SAP ให้ข้อมูลตัวอย่าง ...
python app/tools/seed_sapcode.py
echo [7/8] เพิ่มคอลัมน์เหตุผลความแม่นยำ OCR ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/04_confidence_note.sql
echo [8/9] สร้างตารางประวัติแชทสั่งแก้ไขข้อมูล ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/05_chat.sql
echo [9/10] เพิ่มคอลัมน์เก็บจำนวน Token ที่ใช้อ่านเอกสาร ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/06_tokens.sql
echo [10/11] เพิ่มคอลัมน์ประเภทเอกสาร AP Invoice (Trade/Non-Trade) ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/07_apdoccategory.sql
echo [11/12] เพิ่มคอลัมน์ข้อมูล PO ระดับรายการ (Non-Trade มี PO) ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/08_line_extra.sql
echo [12/13] เพิ่มคอลัมน์ค่าใช้จ่ายต่อเอกสารและสกุลเงิน ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/09_ocr_cost.sql
echo [13/13] แยกคอลัมน์ค่าใช้จ่าย input/output ...
sqlcmd -S 1P69044\SQLEXPRESS -U sa -P Install01 -C -d MGT_Document_OCR -f 65001 -b -i sql/10_ocr_cost_split.sql
echo.
echo เสร็จเรียบร้อย
pause
