import { StrictMode, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Mode = 'MGT' | 'GLC';
type Stage = 'mapping' | 'review' | 'success';
type Product = { line:number; ext:string; name:string; material:string; qty:string; unit:string; price:string; matched:boolean };

const initialLines: Product[] = [
  { line:1, ext:'EXT-A01', name:'สารเคมีตัวอย่าง Alpha', material:'MAT-10042 · Alpha Industrial', qty:'10', unit:'KG', price:'100.00', matched:true },
  { line:2, ext:'EXT-B09', name:'สารเคมีตัวอย่าง Beta', material:'MAT-20118 · Beta Plus', qty:'5', unit:'KG', price:'200.00', matched:true },
  { line:3, ext:'EXT-C12', name:'สารเคมีตัวอย่าง Gamma', material:'', qty:'4', unit:'KG', price:'165.00', matched:false },
];

function Mark({type='ok',children}:{type?:'ok'|'warn'|'idle';children:React.ReactNode}) { return <span className={'mark '+type}>{type==='ok'?'✓':type==='warn'?'!':'•'} {children}</span> }
function Stepper({stage,mode}:{stage:Stage;mode:Mode}) { const current=stage==='mapping'?2:3; return <div className="stepper" aria-label="ขั้นตอนการทำงาน">{[
  ['1','อ่านเอกสาร','เสร็จแล้ว'],['2','จับคู่ข้อมูล',current===2?'กำลังทำ':'เสร็จแล้ว'],['3','ตรวจและส่ง',current===3?'กำลังทำ':mode==='MGT'?'ตรวจต่อในขั้นนี้':'รอผลจับคู่']
].map(([n,t,s],i)=><div key={n} className={'step '+(i+1<current?'done':i+1===current?'active':'')} aria-current={i+1===current?'step':undefined}><span>{i+1<current?'✓':n}</span><div><b>{t}</b><small>{s}</small></div></div>)}</div> }

function Mapping({mode,lines,setLines,aiApplied,setAiApplied,onNext}:{mode:Mode;lines:Product[];setLines:(v:Product[])=>void;aiApplied:boolean;setAiApplied:(v:boolean)=>void;onNext:()=>void}) { const [dealFound,setDealFound]=useState(()=>new URLSearchParams(location.search).get('deal')!=='missing'); const [accountAlt,setAccountAlt]=useState(false); const [shipAlt,setShipAlt]=useState(false); const [deal,setDeal]=useState('D-DEMO-02'); const [showDeal,setShowDeal]=useState(false); const [newMap,setNewMap]=useState(false); const [mappingType,setMappingType]=useState<'customer'|'shipto'|'material'>('material'); const [unitEdit,setUnitEdit]=useState(false); const [aiOpen,setAiOpen]=useState(false); const [aiReady,setAiReady]=useState(false); const canContinue=mode==='GLC'||dealFound; const searchSystem=(mt:'customer'|'shipto'|'material')=>mt==='material'?'SAP':(mode==='MGT'?'Zoho':'SAP'); return <>
  <header className="page-head"><div><p className="kicker">เอกสาร PO-DEMO-026</p><h1>จับคู่ข้อมูลกับข้อมูลหลัก</h1><p>ตรวจข้อมูลสำคัญก่อนเตรียม Sales Order</p></div><div className="page-count">ขั้นตอน <b>2</b> จาก 3</div></header>
  <section className={'notice '+(mode==='MGT'&&!dealFound?'notice-blocked':'')}><div className="notice-icon">{mode==='MGT'&&!dealFound?'!':'✓'}</div><div><b>{mode==='MGT'?(dealFound?'พบ Account และ Deal ที่พร้อมใช้งาน':'พบ Account แล้ว แต่ยังไม่พบ Deal ที่เปิดอยู่'):'พบ SAP Account Code แล้ว'}</b><p>{mode==='MGT'?(dealFound?'ระบบจะสร้าง Sales Order และเชื่อมกับ Deal ที่เลือก':'ต้องเลือกหรือสร้าง Deal ก่อน ระบบจึงจะเตรียม Sales Order ได้'):'ข้อมูลลูกค้าพร้อมส่งตรงตามขั้นตอน SAP'}</p></div><button disabled={!canContinue} onClick={onNext}>{mode==='MGT'?'ตรวจ Sales Order':'ไปตรวจหน่วย'} <span>→</span></button></section>
  <section className="route-card"><div className="route-head"><div><p className="kicker">เส้นทางข้อมูลจริง</p><h2>{mode==='MGT'?'Zoho CRM · Sales Order ต้องอ้างอิง Deal':'SAP S/4HANA · ส่งด้วย Account Code โดยตรง'}</h2></div>{mode==='MGT'&&<button className="text-btn" onClick={()=>setDealFound(!dealFound)}>ดูกรณี{dealFound?'ไม่พบ':'พบ'} Deal</button>}</div><div className="route-steps"><div className="route-step done"><span>1</span><div><small>ACCOUNT</small><b>{mode==='MGT'?'Zoho Account Code':'SAP Account Code'}</b><p>{mode==='MGT'?'ACC-DEMO-1000670':'SAP-DEMO-1000670'}</p></div></div><i>→</i>{mode==='MGT'&&<><div className={'route-step '+(dealFound?'done':'blocked')}><span>2</span><div><small>LOOKUP</small><b>{dealFound?'พบ Open Deal 2 รายการ':'ไม่พบ Open Deal'}</b><p>{dealFound?'เลือก Deal ที่ Sales Order นี้อยู่':'ค้นหาด้วย Zoho Account Code'}</p></div></div><i>→</i></>}<div className={'route-step '+(canContinue?'ready':'waiting')}><span>{mode==='MGT'?3:2}</span><div><small>DESTINATION</small><b>Sales Order</b><p>{canContinue?(mode==='MGT'?'เชื่อมกับ Deal ที่เลือก':'พร้อมส่งเข้า SAP'):'รอ Deal ก่อน'}</p></div></div></div></section>
  <div className="workflow-section-head map-zone"><span>1</span><div><small>MASTER DATA MAPPING</small><h2>จับคู่ข้อมูลกับข้อมูลในระบบ</h2><p>การเลือกหรือเพิ่มค่าในส่วนนี้สามารถบันทึกลง Master Mapping เพื่อใช้กับเอกสารครั้งถัดไป</p></div></div><div className="master-rule"><span>MASTER MAPPING</span><b>ไม่พบค่า → ค้นหาใน SAP → ผู้ใช้เลือก → บันทึกไว้ใช้ครั้งถัดไป</b><small>ใช้กฎนี้กับ Customer, Ship-to, Material และ Unit · ไม่มีการแก้ซ้ำในขั้นตอนถัดไป</small></div><section className="lookup-logic"><div><span>1</span><section><small>CUSTOMER</small><b>Tax ID</b><i>ถ้าไม่พบ</i><b>Customer Name</b><i>ถ้ายังไม่พบ</i><b>ค้น SAP</b></section></div><em>→</em><div><span>2</span><section><small>SHIP-TO</small><b>Ship-to Name</b><i>ถ้าไม่พบ</i><b>Ship-to Address</b><i>ถ้ายังไม่พบ</i><b>ค้น SAP</b></section></div><em>→</em><div><span>3</span><section><small>MATERIAL</small><b>Customer + Material Name</b><i>ถ้าไม่พบ</i><b>ค้นหาใน SAP</b></section></div></section><div className="summary-row"><div><small>รายการที่ต้องตรวจ</small><strong>1</strong><span>จาก 4 ส่วน</span></div><div><small>จับคู่แล้ว</small><strong>3</strong><span>พร้อมใช้งาน</span></div><div><small>ปลายทาง</small><strong>{mode==='MGT'?'Zoho':'SAP'}</strong><span>{mode==='MGT'?'Sales Order':'S/4HANA'}</span></div></div>
  <section className="entity-card"><div className="entity-title"><div className="number">1</div><div><h2>บัญชีลูกค้า <em>Customer Account</em></h2><p>ตรวจจากเลขผู้เสียภาษีและชื่อในเอกสาร</p></div><Mark>{accountAlt?'เลือกโดยคุณ':'จับคู่โดยอัตโนมัติ'}</Mark></div><div className="compare"><div><label>ข้อมูลจากเอกสาร</label><b>บริษัท ลูกค้าตัวอย่าง จำกัด</b><p>เลขผู้เสียภาษี 0100000000000</p></div><div className="flow-arrow">→</div><div><label>{mode==='MGT'?'Zoho Account Code':'SAP Account Code'}</label><select className="master-select" value={accountAlt?'ACC-DEMO-1000821':'ACC-DEMO-1000670'} onChange={e=>{if(e.target.value==='__sap__'){setMappingType('customer');setNewMap(true)}else setAccountAlt(e.target.value==='ACC-DEMO-1000821')}}><option value="ACC-DEMO-1000670">ACC-DEMO-1000670 · บริษัท ลูกค้าตัวอย่าง จำกัด · สำนักงานใหญ่</option><option value="ACC-DEMO-1000821">ACC-DEMO-1000821 · บริษัท ลูกค้าตัวอย่าง จำกัด · สาขาระยอง</option><option value="__sap__">ไม่พบค่าที่ต้องการ — ค้นหาใน SAP…</option></select><small className="db-source">ตัวเลือกจาก Master Mapping Database</small></div></div></section>
  <section className="entity-card"><div className="entity-title"><div className="number">2</div><div><h2>สถานที่จัดส่ง <em>Ship-to</em></h2><p>เลือกจาก Master Mapping หรือค้นหาเพิ่มใน SAP</p></div><Mark>พร้อมส่ง</Mark></div><div className="partner-grid"><div><label>SHIP-TO</label><select className="master-select" value={shipAlt?'ST-DEMO-03':'ST-DEMO-02'} onChange={e=>{if(e.target.value==='__sap__'){setMappingType('shipto');setNewMap(true)}else setShipAlt(e.target.value==='ST-DEMO-03')}}><option value="ST-DEMO-02">ST-DEMO-02 · คลังสินค้าบางนา</option><option value="ST-DEMO-03">ST-DEMO-03 · โรงงานระยอง</option><option value="__sap__">ไม่พบค่าที่ต้องการ — ค้นหาใน SAP…</option></select><p>{shipAlt?'99 ถนนสุขุมวิท ตำบลมาบตาพุด ระยอง 21150':'88 ถนนสุขุมวิท เขตบางนา กรุงเทพมหานคร 10260'}</p><small className="db-source">ตัวเลือกจาก Master Mapping Database</small></div></div><div className="partner-actions"><span>Ship-to Code และที่อยู่จะถูกส่งไปยัง {mode==='MGT'?'Zoho Sales Order':'SAP Partner Functions'}</span></div></section>
  {mode==='MGT'&&<section className={'entity-card '+(!dealFound?'attention':'')}><div className="entity-title"><div className="number">3</div><div><h2>ค้นหา Deal จาก Account <em>Deal lookup</em></h2><p>ค้นหาด้วย Zoho Account Code: {accountAlt?'ACC-DEMO-1000821':'ACC-DEMO-1000670'}</p></div><Mark type={dealFound?'ok':'warn'}>{dealFound?'พบ 2 Deal':'ไม่พบ Deal'}</Mark></div>{dealFound?<><div className="deal"><div><label htmlFor="deal">เลือก Deal ที่ Sales Order นี้อยู่</label><select id="deal" value={deal} onChange={e=>setDeal(e.target.value)}><option value="D-DEMO-02">D-DEMO-02 · งานขายเดือนกันยายน 2026</option><option value="D-DEMO-01">D-DEMO-01 · งานขายประจำไตรมาส 3</option></select></div><div className="deal-info"><span>สถานะ: Open</span><span>{deal==='D-DEMO-02'?'3':'5'} รายการสินค้า</span><button className="text-btn" onClick={()=>setShowDeal(!showDeal)}>{showDeal?'ซ่อนรายละเอียด':'เปิดดู Deal'}</button></div></div>{showDeal&&<div className="deal-preview"><b>{deal} · รายละเอียด Deal</b><span>Account: {accountAlt?'ACC-DEMO-1000821':'ACC-DEMO-1000670'}</span><span>Expected delivery: {deal==='D-DEMO-02'?'18 ก.ย. 2026':'30 ก.ย. 2026'}</span><span>Stage: Proposal / Price Quote</span></div>}</>:<div className="empty-deal"><div>⌕</div><section><b>Account นี้ยังไม่มี Open Deal</b><p>เลือก Deal อื่น หรือสร้าง Deal ใน Zoho แล้วกลับมาค้นหาใหม่</p></section><button className="secondary" onClick={()=>setDealFound(true)}>ค้นหาอีกครั้ง</button></div>}</section>}
  <section className="entity-card attention"><div className="entity-title"><div className="number">{mode==='MGT'?4:3}</div><div><h2>สินค้าและหน่วย <em>Material & Unit Mapping</em></h2><p>แก้ไขค่าที่นี่ก่อนเข้าสรุป ระบบค้นจาก Master Mapping ก่อน หากไม่พบจะค้นต่อใน SAP</p></div><Mark type="warn">ต้องเพิ่ม 1 mapping</Mark></div><div className="mapping-table"><div className="map-head"><span>ค่าจากเอกสาร</span><span>ผลจาก Master Mapping</span><span>หน่วยที่จะส่ง</span><span>การจัดการ</span></div>{lines.map(l=><div className={'map-row '+(!l.matched?'missing':'')} key={l.line}><div><small>บรรทัด {String(l.line).padStart(2,'0')}</small><b>{l.ext} · {l.name}</b><span>{l.qty} {l.unit}</span></div><div>{l.matched?<><Mark>พบจาก Master Mapping</Mark><select className="master-select" value={l.material} onChange={e=>{if(e.target.value==='__sap__'){setMappingType('material');setNewMap(true)}else setLines(lines.map(x=>x.line===l.line?{...x,material:e.target.value}:x))}}><option>{l.material}</option><option>MAT-10078 · Epoxy Resin</option><option>MAT-30101 · Gamma Standard</option><option value="__sap__">ไม่พบค่าที่ต้องการ — ค้นหาใน SAP…</option></select><small className="db-source">จาก Master Mapping Database</small></>:<><Mark type="warn">ไม่พบใน Master Mapping</Mark><span>ยังไม่มีรหัสสินค้าที่บันทึกไว้</span></>}</div><div><b>{l.qty}</b><select className="master-select unit-select" value={l.unit} onChange={e=>{if(e.target.value==='__sap__')setUnitEdit(true);else setLines(lines.map(x=>x.line===l.line?{...x,unit:e.target.value}:x))}}><option>KG</option><option>TO</option><option>EA</option><option value="__sap__">ไม่พบหน่วย — ค้นหาใน SAP…</option></select></div><div>{l.matched?<Mark>พร้อมใช้</Mark>:<button className="primary" onClick={()=>{setMappingType('material');setNewMap(true)}}>ค้นหาใน SAP</button>}</div></div>)}</div><div className="mapping-note">เมื่อเลือกค่าจาก SAP และกดบันทึก ระบบจะเพิ่มคู่ค่า Document → SAP Master Data ลงใน Master Mapping เพื่อใช้แนะนำอัตโนมัติครั้งถัดไป</div></section>
  {newMap&&<div className="overlay" role="dialog" aria-modal="true"><div className="modal"><div className="modal-head"><div><p className="kicker">MASTER MAPPING</p><h2>ค้นหา {mappingType==='customer'?'Customer':mappingType==='shipto'?'Ship-to':'Material'} ใน {searchSystem(mappingType)}</h2></div><button onClick={()=>setNewMap(false)}>×</button></div><div className="mapping-form"><label>ค่าที่หาไม่พบใน Master Mapping<input value={mappingType==='customer'?'บริษัท ลูกค้าตัวอย่าง จำกัด':mappingType==='shipto'?'คลังสินค้าบางนา · กรุงเทพมหานคร':'บริษัท ลูกค้าตัวอย่าง จำกัด · สารเคมีตัวอย่าง Gamma'} readOnly/></label><label>ผลการค้นหาจาก {searchSystem(mappingType)}<select defaultValue="primary">{mappingType==='customer'?<><option value="primary">1000670 · บริษัท ลูกค้าตัวอย่าง จำกัด</option><option>1000821 · บริษัท ลูกค้าตัวอย่าง จำกัด · สาขาระยอง</option></>:mappingType==='shipto'?<><option value="primary">1000673 · คลังสินค้าบางนา</option><option>1000830 · โรงงานระยอง</option></>:<><option value="primary">MAT-10078 · Epoxy Resin</option><option>MAT-30101 · Gamma Standard</option></>}</select></label><label>หน่วยที่ระบบปลายทางรับ<select defaultValue="KG"><option>KG</option><option>TO</option></select></label><label className="remember"><input type="checkbox" defaultChecked/> บันทึก mapping นี้ไว้ใช้กับเอกสารครั้งถัดไป</label></div><div className="modal-actions"><button className="cancel" onClick={()=>setNewMap(false)}>ยกเลิก</button><button className="primary" onClick={()=>{if(mappingType==='customer')setAccountAlt(false);else if(mappingType==='shipto')setShipAlt(false);else setLines(lines.map(l=>l.line===3?{...l,matched:true,material:'MAT-10078 · Epoxy Resin',unit:'KG'}:l));setNewMap(false)}}>เลือกจาก {searchSystem(mappingType)} และบันทึก Mapping</button></div></div></div>}
  {unitEdit&&<div className="overlay" role="dialog" aria-modal="true"><div className="modal unit-modal"><div className="modal-head"><div><p className="kicker">UNIT MAPPING</p><h2>ตรวจและแปลงหน่วย</h2></div><button onClick={()=>setUnitEdit(false)}>×</button></div><div className="conversion-card"><div><small>หน่วยจากเอกสาร</small><b>Kilogram</b><span>จำนวน 185</span></div><i>→</i><div><small>หน่วยปลายทาง</small><select defaultValue="KG"><option>KG</option><option>TO</option></select><span>Material: MAT-10078</span></div></div><div className="formula"><span>อัตราแปลง</span><input defaultValue="1"/><b>Kilogram =</b><input defaultValue="1"/><b>KG</b></div><div className="conversion-result"><span>ค่าที่จะส่ง</span><strong>185 KG</strong><Mark>พร้อมใช้</Mark></div><div className="modal-actions"><button className="cancel" onClick={()=>setUnitEdit(false)}>ยกเลิก</button><button className="primary" onClick={()=>setUnitEdit(false)}>บันทึก Unit Mapping</button></div></div></div>}
  {aiOpen&&<div className="overlay" role="dialog" aria-modal="true" aria-label="AI Document Assistant"><div className="modal ai-chat"><div className="modal-head"><div><p className="kicker">AI DOCUMENT ASSISTANT</p><h2>แก้ข้อมูลเอกสารด้วยภาษาธรรมดา</h2></div><button onClick={()=>setAiOpen(false)}>×</button></div><div className="chat-history"><div className="ai-message">บอกข้อมูลที่ต้องการแก้ได้เลย เช่น “เปลี่ยนวันส่งเป็น 20 กันยายน และ Incoterms เป็น DDP”</div>{aiReady&&<div className="change-preview"><b>AI เสนอการเปลี่ยนแปลง 2 จุด</b><div><span>Requested Delivery Date</span><del>18 ก.ย. 2026</del><strong>20 ก.ย. 2026</strong></div><div><span>Incoterms</span><del>DAP</del><strong>DDP</strong></div><small>ใช้กับเอกสารนี้เท่านั้น · ไม่เปลี่ยน Master Mapping</small></div>}</div><div className="chat-compose"><textarea defaultValue="เปลี่ยนวันส่งเป็น 20 กันยายน และ Incoterms เป็น DDP"/><button className="secondary" onClick={()=>setAiReady(true)}>ให้ AI วิเคราะห์</button></div>{aiReady&&<div className="modal-actions"><button className="cancel" onClick={()=>setAiReady(false)}>แก้คำสั่ง</button><button className="primary" onClick={()=>{setAiApplied(true);setAiOpen(false)}}>ยืนยันใช้ 2 การเปลี่ยนแปลง</button></div>}</div></div>}<div className="sticky-action"><div><b>{mode==='MGT'?(dealFound?'พร้อมประกอบ Sales Order · ยังไม่ได้ส่งข้อมูล':'รอเลือก Deal ก่อน'):'ไปเลือกสินค้าและตรวจการแปลงหน่วยต่อ'}</b><small>{mode==='MGT'?(dealFound?'ขั้นตอนถัดไปแสดงค่าที่จะส่ง พร้อม Account และ Deal ที่อ้างอิง':'Sales Order ใน Zoho ต้องเชื่อมกับ Deal ตาม flow เดิม'):'หน้าถัดไปแสดงค่าที่จะส่ง SAP ครบทุกส่วน'}</small></div><button className={canContinue?'primary':'disabled'} disabled={!canContinue} onClick={onNext}>{mode==='MGT'?'ไปตรวจ Sales Order':'ตรวจและแก้ข้อมูล SAP'} <span>→</span></button></div>
 </> }

function Review({mode,lines,setLines,aiApplied,onBack,onSuccess}:{mode:Mode;lines:Product[];setLines:(v:Product[])=>void;aiApplied:boolean;onBack:()=>void;onSuccess:()=>void}) {
 const [modal,setModal]=useState(false); const [unitModal,setUnitModal]=useState(false); const matched=lines.filter(x=>x.matched); const skipped=lines.filter(x=>!x.matched);
 const update=(line:number,key:keyof Product,value:string)=>setLines(lines.map(x=>x.line===line?{...x,[key]:value}:x));
 return <><header className="page-head"><div><button className="back" onClick={onBack}>← กลับไปจับคู่ข้อมูล</button><p className="kicker">PO-DEMO-026 · C-DEMO-01</p><h1>สรุป Sales Order ก่อนส่ง</h1><p>อ่านอย่างเดียว หากต้องการเปลี่ยนค่าให้กลับไปหน้า Mapping</p></div><div className="destination">ส่งไป<br/><b>{mode==='MGT'?'Zoho CRM':'SAP S/4HANA'}</b></div></header> <div className="count-grid"><div><span>รายการในเอกสาร</span><b>{lines.length}</b></div><div className="good"><span>บรรทัดที่จะส่ง</span><b>{matched.length}</b></div><div className="bad"><span>บรรทัดไม่ถูกส่ง</span><b>{skipped.length}</b></div></div>
 <section className="send-context"><div><small>SOLD-TO PARTY</small><b>{mode==='MGT'?'ACC-DEMO-1000670':'1000670'}</b><span>บริษัท ลูกค้าตัวอย่าง จำกัด</span></div><i>+</i><div><small>SHIP-TO PARTY</small><b>{mode==='MGT'?'ST-DEMO-02':'1000673'}</b><span>คลังสินค้าบางนา</span></div>{mode==='MGT'&&<><i>+</i><div><small>DEAL LOOKUP</small><b>D-DEMO-02</b><span>ค้นจาก Zoho Account Code</span></div></>}<strong>จะส่งไป {mode==='MGT'?'Zoho':'SAP'}</strong></section>
 {skipped.length>0&&<section className="warning"><span>!</span><div><b>บรรทัด {skipped.map(x=>x.line).join(', ')} ยังไม่จับคู่และจะไม่ถูกส่ง</b><p>ส่งเฉพาะรายการที่พร้อมได้ หรือเลือกสินค้าให้ครบก่อน</p></div><button onClick={()=>setModal(true)}>เลือกสินค้า</button></section>}
 <section className="form-card summary-card"><div className="section-head"><div><h2>ข้อมูล Header ที่จะส่งจริง</h2><p>ใช้ชื่อฟิลด์เดียวกับกระบวนการ SAP พร้อมคำอธิบายที่อ่านง่าย</p></div><Mark type="ok">ยืนยันจาก Mapping แล้ว</Mark></div><div className="payload-tabs"><button className="active">Header</button><button onClick={()=>document.getElementById('line-items')?.scrollIntoView({behavior:'smooth'})}>Items</button><span>{mode==='MGT'?'Zoho เพิ่ม Account และ Deal reference':'Create Sales Order (VA01)'}</span></div><div className="form-grid payload-grid"><label className="locked-source"><span>Sold-to Party <i>ลูกค้าที่สั่งซื้อ</i></span><input readOnly defaultValue={mode==='MGT'?'ACC-DEMO-1000670':'1000670'}/><small>จาก Customer Account ที่จับคู่แล้ว</small></label><label className="locked-source"><span>Ship-to Party <i>สถานที่จัดส่ง</i></span><input readOnly defaultValue={mode==='MGT'?'ST-DEMO-02':'1000673'}/><small>จาก Ship-to ที่เลือก</small></label>{mode==='MGT'&&<label className="locked-source"><span>Deal <i>งานขายที่อ้างอิง</i></span><select disabled defaultValue="D-DEMO-02"><option>D-DEMO-02</option><option>D-DEMO-01</option></select><small>🔒 มาจาก Mapping · กลับไปแก้ในส่วนที่ 1</small></label>}<label><span>Customer Reference <i>เลข PO ลูกค้า</i></span><input defaultValue="PO-DEMO-026"/><small>อ่านจากเอกสาร</small></label><label><span>Customer Ref. Date <i>วันที่เอกสาร</i></span><input type="date" defaultValue="2026-09-10"/><small>อ่านจากเอกสาร</small></label><label><span>Requested Delivery Date <i>วันที่ลูกค้าต้องการสินค้า</i></span><input type="date" defaultValue={aiApplied?'2026-09-20':'2026-09-18'}/><small>อ่านจากเอกสาร หรือใช้ค่าเดิมตามกฎ</small></label><label><span>Payment Terms <i>เงื่อนไขชำระเงิน</i></span><select defaultValue="NET30"><option value="NET30">NET30 · ชำระภายใน 30 วัน</option><option value="NT08">NT08 · Net due in 8 days</option></select><small>จาก Account/Deal หรือข้อมูลหลัก</small></label><label><span>Currency <i>สกุลเงิน</i></span><select defaultValue="THB"><option>THB</option><option>USD</option></select><small>ค่าที่จะส่ง: THB</small></label><label><span>Incoterms <i>เงื่อนไขส่งมอบ</i></span><input defaultValue={aiApplied?'DDP':'DAP'}/><small>จาก Account หรือข้อมูลหลัก</small></label></div><div className="fallback">ⓘ ทุกช่องด้านบนคือค่าที่ระบบจะส่งจริง หากใช้ค่าเดิม ระบบจะแสดงแหล่งที่มาของค่านั้นก่อนส่ง</div></section>
 <section className="form-card summary-card" id="line-items"><div className="section-head"><div><h2>ข้อมูล Items ที่จะส่งจริง</h2><p>Material, Order Quantity, Unit และราคาของแต่ละ Line Item</p></div><button className="text-btn">ไปบรรทัดที่ต้องตรวจ ({skipped.length})</button></div><div className="product-table"><div className="tr header"><span>บรรทัด</span><span>เอกสาร → สินค้าในระบบ</span><span>จำนวน</span><span>หน่วย</span><span>ราคา/หน่วย</span><span>ผลต่อการส่ง</span></div>{lines.map(l=><div className={'tr '+(!l.matched?'needs':'')} key={l.line}><span className="line-no">{String(l.line).padStart(2,'0')}</span><span><b>{l.ext} · {l.name}</b>{l.matched?<small>↓ {l.material}</small>:<small>ยังไม่มีสินค้าที่เลือก</small>}</span><span>{l.matched?<input aria-label={'จำนวน บรรทัด '+l.line} value={l.qty} onChange={e=>update(l.line,'qty',e.target.value)}/>:<i>—</i>}</span><span>{l.matched?<input aria-label={'หน่วย บรรทัด '+l.line} value={l.unit} onChange={e=>update(l.line,'unit',e.target.value)}/>:<i>—</i>}</span><span>{l.matched?<input aria-label={'ราคา บรรทัด '+l.line} value={l.price} onChange={e=>update(l.line,'price',e.target.value)}/>:<i>—</i>}</span><span>{l.matched?<Mark>จะส่ง</Mark>:<button className="match-btn" onClick={()=>setModal(true)}>เลือกสินค้า</button>}</span></div>)}</div></section>
 <div className="send-panel"><div><span className="send-icon">↗</span><div><b>ส่ง {matched.length} จาก {lines.length} บรรทัดไป {mode==='MGT'?'Zoho CRM':'SAP'}</b><small>{skipped.length?`บรรทัด ${skipped.map(x=>x.line).join(', ')} จะไม่ถูกส่ง`:'ตรวจครบทุกบรรทัดแล้ว'}</small></div></div><button className="primary" onClick={onSuccess}>ส่ง {matched.length} บรรทัด</button></div>
 {unitModal&&<div className="overlay" role="dialog" aria-modal="true" aria-label="แปลงหน่วยสำหรับ SAP"><div className="modal unit-modal"><div className="modal-head"><div><p className="kicker">SAP · UNIT CONVERSION</p><h2>ตรวจและแปลงหน่วยก่อนส่ง</h2></div><button aria-label="ปิด" onClick={()=>setUnitModal(false)}>×</button></div><div className="conversion-card"><div><small>หน่วยจากเอกสาร</small><b>Kilogram</b><span>จำนวน 185</span></div><i>→</i><div><small>หน่วยที่ SAP รับ</small><select defaultValue="KG"><option>KG</option><option>TO</option></select><span>Material: MAT-10078</span></div></div><div className="formula"><span>อัตราแปลง</span><input defaultValue="1"/><b>Kilogram =</b><input defaultValue="1"/><b>KG</b></div><div className="conversion-result"><span>จำนวนที่จะส่ง SAP</span><strong>185 KG</strong><Mark>พร้อมส่ง</Mark></div><div className="modal-actions"><button className="cancel" onClick={()=>setUnitModal(false)}>ยกเลิก</button><button className="primary" onClick={()=>{setLines(lines.map(l=>l.line===3?{...l,matched:true,material:'MAT-10078 · Epoxy Resin',unit:'KG'}:l));setUnitModal(false)}}>ใช้หน่วยนี้</button></div></div></div>} {modal&&<div className="overlay" role="dialog" aria-modal="true" aria-label="เลือกสินค้าให้บรรทัด 3"><div className="modal"><div className="modal-head"><div><p className="kicker">บรรทัด 03 · Deal D-DEMO-02</p><h2>เลือกสินค้าให้ “Gamma”</h2></div><button aria-label="ปิด" onClick={()=>setModal(false)}>×</button></div><div className="doc-chip">จากเอกสาร: <b>EXT-C12 · สารเคมีตัวอย่าง Gamma · 4 KG</b></div><div className="ai-hint"><span>✦</span><div><b>เลือกเองได้ หรือให้ AI ช่วยเปรียบเทียบ</b><p>คำแนะนำจะไม่เปลี่ยนรายการจนกว่าคุณกดใช้สินค้านี้</p></div><button>ให้ AI ช่วยเสนอ</button></div>{['MAT-30101 · Gamma Standard','MAT-30108 · Gamma Premium'].map((x,i)=><div className="candidate" key={x}><div className="radio">{i===0?'●':'○'}</div><div><b>{x}</b><p>{i===0?'ชื่อและหน่วยตรงกัน · ควรตรวจเกรดสินค้า':'ชื่อใกล้เคียง · รายละเอียดเกรดต่างกัน'}</p></div><span className={'score '+(i?'medium':'high')}>{i?'72':'91'}%</span><button onClick={()=>{setLines(lines.map(l=>l.line===3?{...l,matched:true,material:x}:l));setModal(false)}}>ใช้สินค้านี้</button></div>)}<button className="cancel" onClick={()=>setModal(false)}>ยกเลิกและกลับไปตรวจรายการ</button></div></div>}
 </> }

function Success({mode,count,onReset}:{mode:Mode;count:number;onReset:()=>void}) { return <div className="success-page"><div className="success-orb">✓</div><p className="kicker">ส่งข้อมูลสำเร็จ</p><h1>สร้าง Sales Order แล้ว</h1><p>ระบบส่ง {count} บรรทัดไป {mode==='MGT'?'Zoho CRM':'SAP S/4HANA'} เรียบร้อย</p><div className="receipt"><div><span>เลขอ้างอิง</span><b>{mode==='MGT'?'ZOHO-SO-DEMO-026':'SAP-SO-DEMO-026'}</b></div><div><span>บริษัท</span><b>{mode}</b></div><div><span>สถานะ</span><Mark>สำเร็จ</Mark></div></div><button className="primary" onClick={onReset}>กลับไปดูต้นแบบอีกครั้ง</button></div> }

function App(){ const [mode,setMode]=useState<Mode>(()=>new URLSearchParams(location.search).get('mode')==='GLC'?'GLC':'MGT'); const [stage,setStage]=useState<Stage>(()=>new URLSearchParams(location.search).get('screen')==='review'?'review':'mapping'); const [lines,setLines]=useState(initialLines); const [aiApplied,setAiApplied]=useState(false); const [theme,setTheme]=useState<'light'|'dark'>('light'); const matched=useMemo(()=>lines.filter(x=>x.matched).length,[lines]); return <div className="app" data-theme={theme}><aside><div className="logo"><div>M</div><span><b>MGT</b><small>DOCUMENT OCR</small></span></div><nav><a className="active">▦ <span>เอกสารงานขาย</span></a><a>▤ <span>รายการเอกสาร</span></a><a>⌘ <span>ข้อมูลหลัก</span></a><a>◷ <span>ประวัติการส่ง</span></a></nav><div className="theme-row"><span>{theme==='dark'?'โหมดมืด':'โหมดสว่าง'}</span><button className={'theme-toggle '+(theme==='dark'?'dark':'')} aria-label="สลับโหมดสว่าง/มืด" onClick={()=>setTheme(theme==='dark'?'light':'dark')}><i className="tt-sun">☀</i><i className="tt-moon">☾</i><span className="tt-knob"></span></button></div><div className="user"><div>SK</div><span><b>ผู้ใช้งานตัวอย่าง</b><small>Sales Operations</small></span></div></aside><main><div className="topbar"><div><span className="mobile-logo">MGT OCR</span><b>Sales Order</b><span className="crumb">/ PO-DEMO-026</span></div><div className="mode-switch" aria-label="บริษัทที่กำลังทำงาน"><button className={mode==='MGT'?'active':''} onClick={()=>{setMode('MGT');setStage('mapping')}}>MGT <small>Zoho</small></button><button className={mode==='GLC'?'active':''} onClick={()=>{setMode('GLC');setStage('mapping')}}>GLC <small>SAP</small></button></div></div><div className="company-bar"><span className="pulse"></span><b>บริษัทที่กำลังทำงาน: {mode}</b><span>ข้อมูลจะส่งไป {mode==='MGT'?'Zoho CRM':'SAP S/4HANA'}</span></div><Stepper stage={stage} mode={mode}/><div className="workspace">{stage==='mapping'?<Mapping mode={mode} lines={lines} setLines={setLines} aiApplied={aiApplied} setAiApplied={setAiApplied} onNext={()=>setStage('review')}/>:stage==='review'?<Review mode={mode} lines={lines} setLines={setLines} aiApplied={aiApplied} onBack={()=>setStage('mapping')} onSuccess={()=>setStage('success')}/>:<Success mode={mode} count={matched} onReset={()=>{setLines(initialLines);setStage('mapping')}}/>}</div></main></div> }

createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);






















